[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Configurações para as funções
[functions]
  node_bundler = "esbuild"

# Plugin para instalar dependências das funções
[[plugins]]
  package = "@netlify/plugin-functions-install-core"