uploads = []
generated = []

[[outputs]]
id = "f8OWt9htdzTifU0jnDr1x"
uri = "file://firestore-rules.txt"
type = "text"
title = "Regras do Firestore (cole no Firebase Console → Firestore → Rules)"

[[outputs]]
id = "gjvTQoqdXQDTG8X17jqBo"
uri = "file://storage-rules.txt"
type = "text"
title = "Regras do Storage (cole no Firebase Console → Storage → Rules)"
