uploads = []
generated = []

[[outputs]]
id = "f8OWt9htdzTifU0jnDr1x"
uri = "file://firestore-rules.txt"
type = "text"
title = "firestore-rules.txt — Cole no Firebase Console"

[[outputs]]
id = "gjvTQoqdXQDTG8X17jqBo"
uri = "file://storage-rules.txt"
type = "text"
title = "Storage Rules (txt para copiar)"

[[outputs]]
id = "OPuyyWKe2p3lRpKci1Agm"
uri = "file://xtreino-admin-update.tar.gz"
type = "unspecified"
title = "xtreino-admin-update.tar.gz — todos os arquivos atualizados"
